services:
  nginx:
    ports:
      - '443:443'
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    environment:
      - SSL_CERT_PATH=/etc/letsencrypt
      - SSL_WWW_PATH=/var/www/certbot
